version: "3.1"

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: db_name
  neo4:
    image: neo4j:4.2.0
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4JLABS_PLUGINS: ["apoc", "graph-algorithms"]
    # --volume=$HOME/neo4j/data:/data \
    # --volume=$HOME/neo4j/logs:/logs \
