version: '3.1'

services:

  db:
    image: postgres:12-alpine  # mdillon/postgis:9.6
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: db_name
