apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: wurstmeister/kafka:2.12-2.4.1
          name: kafka
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 10.32.11.39
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_OFFSETS_RETENTION_MINUTES
              value: "10080"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "43800"
            - name: KAFKA_NUM_PARTITIONS
              value: "16"
            - name: KAFKA_PORT
              value: "9092"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP