apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - image: neo4j:4.2.0
          name: neo4j
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
          ports:
          - containerPort: 7474
          - containerPort: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-web
spec:
  type: LoadBalancer
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      name: web-port
      port: 7474
      targetPort: 7474
    - protocol: TCP
      name: rpc-port
      port: 7687
      targetPort: 7687