apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-slave
spec:
  replicas: 12
  selector:
    matchLabels:
      app: backend-slave
  template:
    metadata:
      labels:
        app: backend-slave
    spec:
      containers:
        - image: matematyk60/crawler-service:0.7
          name: backend-slave
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: KAFKA_HOST
              value: 10.60.5.51
            - name: KAFKA_PORT
              value: "9092"
      restartPolicy: Always