apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-slavejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-slavejs
  template:
    metadata:
      labels:
        app: backend-slavejs
    spec:
      containers:
        - image: porcupine96/puppeteer-crawler:0.5
          name: backend-slavejs
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: redis://redis
            - name: KAFKA_HOST
              value: 10.60.5.51
            - name: KAFKA_PORT
              value: "9092"
      restartPolicy: Always